export interface Flashcard {
  q: string;
  a: string;
}

export interface FlashcardTopic {
  topic: string;
  icon: string;
  cards: Flashcard[];
}

export const FLASHCARD_TOPICS: FlashcardTopic[] = [
  {
    topic: "Use Cases",
    icon: "📋",
    cards: [
      { q: "Hvad er en use case?", a: "En tekstbaseret beskrivelse af hvad et system gør, trin for trin i detaljer." },
      { q: "Hvad er forskellen på Brief, Casual og Fully Dressed?", a: "Brief er en hurtig opsummering brugt tidligt i processen. Casual tilføjer et hovedforløb og alternativer. Fully Dressed er den mest detaljerede form med preconditions, main flow og alternative flows." },
      { q: "Hvornår bruger man Fully Dressed?", a: "Til komplekse use cases, hvor man skal fortælle alt hvad systemet skal gøre i hver situation." },
      { q: "Hvad er en Primary Actor?", a: "Den vigtigste bruger, som starter interaktionen med systemet." },
      { q: "Hvad er en Supporting Actor?", a: "En aktør der assisterer systemet eller primary actor — typisk eksterne systemer eller andre brugere." },
      { q: "Hvad er en Offstage Actor?", a: "En aktør der ikke er direkte involveret i interaktionen, men som har en interesse i resultatet." },
      { q: "Hvad er et Main Success Scenario?", a: "Et scenarie hvor alt fungerer som det skal, og primary actor når sit mål." },
      { q: "Hvad er forskellen på Alternative Flow og Error Flow?", a: "Alternative flow er afvigelser der stadig leder til succes. Error flow er scenarier hvor noget går galt, og viser hvordan systemet håndterer problemet." },
      { q: "Hvad er formålet med et use case diagram?", a: "At understøtte den tekstbaserede use case visuelt." },
    ],
  },
  {
    topic: "Scrum",
    icon: "🔄",
    cards: [
      { q: "Hvad er empirisme i Scrum?", a: "At træffe beslutninger baseret på observation, erfaring og eksperimenter frem for antagelser." },
      { q: "Hvad er forskellen på Product Backlog og Sprint Backlog?", a: "Product Backlog er en prioriteret liste over alt der skal forbedres i produktet, styret af Product Owner. Sprint Backlog er de opgaver der er valgt til det aktuelle sprint, styret af developers." },
      { q: "Hvad er Scrum Masterens rolle?", a: "At facilitere Scrum-praksis, fjerne forhindringer og sikre at teamet følger Scrum-principperne." },
      { q: "Hvad er Product Ownerens rolle?", a: "At administrere og prioritere Product Backlog og sikre at teamet arbejder på værdifulde opgaver." },
      { q: "Hvad er formålet med Daily Scrum?", a: "Et 15-minutters møde hvor developers inspicerer fremskridt mod Sprint Goal og justerer planer." },
      { q: "Hvad er forskellen på Sprint Review og Sprint Retrospective?", a: "Sprint Review gennemgår det færdige arbejde med interessenter. Sprint Retrospective reflekterer over selve sprintprocessen — hvad gik godt og hvad kan forbedres." },
      { q: "Hvad er et Burndown Chart?", a: "En grafisk fremstilling af arbejdet der mangler i forhold til den tilbageværende tid i en sprint." },
      { q: "Hvad er Velocity?", a: "Hvor meget arbejde et team kan udføre inden for et sprint, typisk målt i story points. Bruges til at planlægge næste sprint." },
      { q: "Hvad er Capacity?", a: "Den arbejdsmængde et team kan udføre baseret på antal medlemmer og antal tilgængelige timer." },
      { q: "Hvad er Planning Poker?", a: "En estimeringsteknik hvor teammedlemmer bruger nummererede kort til at stemme om en opgaves kompleksitet, efterfulgt af diskussion for at nå til enighed." },
      { q: "Hvad er de 5 Scrum værdier?", a: "Commitment, Focus, Openness, Respect og Courage." },
      { q: "Hvad er Definition of Done?", a: "Kvalitetsstandarder som hvert inkrement skal opfylde før det betragtes som færdigt." },
      { q: "Hvad er et Sprint Goal?", a: "Et fokuspunkt for sprinten der guider teamet i det arbejde der skal udføres." },
    ],
  },
  {
    topic: "CI/CD & Cloud",
    icon: "☁️",
    cards: [
      { q: "Hvad er formålet med CI/CD?", a: "At automatisere bygge-, test- og udrulningsprocessen for at sikre hurtigere udvikling, færre fejl og en mere stabil kodebase." },
      { q: "Hvad er en virtuel computer?", a: "En softwarebaseret emulering af en fysisk computer der kører et operativsystem isoleret fra den fysiske hardware." },
      { q: "Hvad er en Cloud Instance?", a: "En virtuel server i en cloud-platform som Azure eller AWS, der kan oprettes og skaleres efter behov." },
      { q: "Hvad er Azure App Service?", a: "En PaaS-løsning der gør det muligt at køre webapplikationer og API'er uden at administrere underliggende infrastruktur." },
      { q: "Hvad er GitHub Actions?", a: "En CI/CD-tjeneste der automatiserer workflows som build, test og deployment direkte fra et GitHub repository." },
      { q: "Hvad er YAML og hvornår bruges det?", a: "Et letlæseligt konfigurationsformat brugt i CI/CD pipelines og Kubernetes. Modsat JSON understøtter det kommentarer og er nemmere at læse for mennesker." },
      { q: "Hvordan forbinder man til en Linux Cloud Instance?", a: "Via SSH: ssh user@ip-adresse" },
    ],
  },
  {
    topic: "Docker",
    icon: "🐳",
    cards: [
      { q: "Hvad er Docker?", a: "En containerplatform der gør det muligt at pakke, distribuere og køre applikationer i isolerede miljøer." },
      { q: "Hvad er forskellen på et Docker Image og en Docker Container?", a: "Et image er en statisk skabelon af et miljø. En container er en kørende instans af et image." },
      { q: "Hvad er en Dockerfile?", a: "En fil med instruktioner til at bygge et Docker image." },
      { q: "Hvordan mapper man porte i Docker?", a: "Med -p hostPort:containerPort i docker run kommandoen." },
      { q: "Hvilke alternativer findes der til Docker?", a: "Virtual Machines, Kubernetes og Serverless (fx Azure Functions)." },
      { q: "Hvad gør docker ps -a?", a: "Viser alle containers, også dem der er stoppet." },
      { q: "Hvad gør docker logs container_id?", a: "Viser output fra en kørende eller stoppet container." },
    ],
  },
  {
    topic: "Netværk & Protokoller",
    icon: "🌐",
    cards: [
      { q: "Hvad er forskellen på TCP og UDP?", a: "TCP er pålidelig og sikrer at data leveres korrekt. UDP er hurtigere men uden garanti for levering." },
      { q: "Hvad gør DNS?", a: "Oversætter domænenavne som google.com til IP-adresser." },
      { q: "Hvad gør DHCP?", a: "Tildeler automatisk IP-adresser til enheder på et netværk." },
      { q: "Hvad er en MAC-adresse?", a: "En unik hardware-adresse der identificerer en netværksenhed." },
      { q: "Hvad bruges Wireshark til?", a: "Netværksovervågning — man kan inspicere og analysere pakker på et netværk." },
      { q: "Hvad er en NSG i Azure?", a: "En Network Security Group der fungerer som firewall og styrer hvilken trafik der må ind og ud." },
    ],
  },
  {
    topic: "Domain Model & GRASP",
    icon: "🧩",
    cards: [
      { q: "Hvad er en Domain Model?", a: "En visuel repræsentation af virkelighedens konceptuelle klasser, deres associationer og attributter." },
      { q: "Hvad er en Conceptual Class?", a: "Noget der repræsenterer virkeligheden, fx Book eller Member i et bibliotekssystem. Det er ikke en softwareklasse." },
      { q: "Hvad er Multiplicity i en association?", a: "Et udtryk der angiver hvor mange instanser af én klasse der er relateret til en anden, fx 1-to-many." },
      { q: "Hvad er Information Expert i GRASP?", a: "Et princip hvor en responsibility gives til den klasse der har de nødvendige informationer til at løse den." },
      { q: "Hvad er Low Coupling?", a: "Et princip om at klasser skal være mindst muligt afhængige af hinanden, så ændringer i én klasse ikke påvirker andre." },
      { q: "Hvad er High Cohesion?", a: "Et princip om at en klasse skal fokusere på ét ansvar, så den bliver nem at forstå, teste og vedligeholde." },
      { q: "Hvornår bruger man Pure Fabrication?", a: "Når en responsibility ikke naturligt passer ind i eksisterende klasser uden at bryde High Cohesion eller Low Coupling." },
      { q: "Hvad er Polymorphism i GRASP?", a: "At forskellige klasser kan udføre den samme handling via et fælles interface, så nye klasser kan tilføjes uden at ændre eksisterende kode." },
      { q: "Hvad er Creator-princippet i GRASP?", a: "At ansvaret for at oprette en instans af klasse A gives til klasse B, hvis B indeholder, bruger eller har de data der kræves for at initialisere A." },
    ],
  },
  {
    topic: "Hardware & Software",
    icon: "💻",
    cards: [
      { q: "Hvad er forskellen på RAM og en harddisk?", a: "RAM er korttidshukommelse der slettes når computeren slukkes. En harddisk er langtidshukommelse til permanent lagring." },
      { q: "Hvad er forskellen på HDD og SSD?", a: "HDD er mekanisk, langsommere og billigere. SSD er hurtigere og mere pålidelig, men dyrere." },
      { q: "Hvad er en GPU?", a: "En specialiseret processor der håndterer grafiske beregninger, brugt til spil, videoredigering og kunstig intelligens." },
      { q: "Hvad er et bundkort?", a: "Komponenten der forbinder alle dele af computeren så de kan kommunikere med hinanden." },
      { q: "Hvad måles CPU-hastighed i?", a: "GHz (gigahertz) — jo højere tal, jo hurtigere processor." },
    ],
  },
  {
    topic: "Programmering",
    icon: "👨‍💻",
    cards: [
      { q: "Hvad er forskellen på Java og Python?", a: "Java er statisk typet og kompileret, velegnet til enterprise-systemer. Python er dynamisk typet og fortolket, populær til scripting, data og AI." },
      { q: "Hvad bruges Node.js til?", a: "At køre JavaScript på serveren, ofte til hurtige og skalerbare backend-tjenester." },
      { q: "Hvad er React?", a: "Et JavaScript-bibliotek til at bygge brugergrænseflader, baseret på komponenter." },
      { q: "Hvad er forskellen på HTML og CSS?", a: "HTML definerer strukturen og indholdet på en webside. CSS styler udseendet og layoutet." },
      { q: "Hvad er et framework?", a: "En samling af færdige værktøjer og strukturer der hjælper udviklere med at bygge applikationer hurtigere og mere struktureret." },
    ],
  },
  {
    topic: "Frameworks & API",
    icon: "⚙️",
    cards: [
      { q: "Hvad er Spring Boot?", a: "Et Java-framework der gør det nemt at bygge produktionsklar backend-applikationer og REST API'er." },
      { q: "Hvad er JPA?", a: "Java Persistence API — et interface til at håndtere databaseoperationer i Java uden at skrive rå SQL." },
      { q: "Hvad er Microservices?", a: "En arkitektur hvor en applikation opdeles i små, selvstændige services der kommunikerer via API'er." },
      { q: "Hvad er et REST API?", a: "Et API der bruger HTTP-metoder som GET, POST, PUT og DELETE til at kommunikere mellem systemer." },
      { q: "Hvad er MySQL?", a: "Et relationelt databasesystem der bruger SQL til at oprette, læse, opdatere og slette data." },
    ],
  },
  {
    topic: "Cybersecurity & Pentest",
    icon: "🔐",
    cards: [
      { q: "Hvad er Penetration Testing?", a: "En kontrolleret cyberangreb på et system for at finde sikkerhedssårbarheder, før en rigtig angriber gør det." },
      { q: "Hvad er Kali Linux?", a: "En Linux-distribution designet til penetration testing og sikkerhedsanalyse med mange built-in hackerværktøjer." },
      { q: "Hvad bruges Nmap til?", a: "Til at scanne netværk og finde åbne porte, services og enheder på et netværk." },
      { q: "Hvad er Metasploit?", a: "Et framework til penetration testing der gør det nemt at udnytte kendte sikkerhedssårbarheder." },
      { q: "Hvad er SQL Injection?", a: "Et angreb hvor en angriber indsætter ondsindet SQL-kode i et inputfelt for at manipulere en database." },
      { q: "Hvad er Active Directory?", a: "Microsofts system til at administrere brugere, computere og rettigheder i et netværk." },
      { q: "Hvad er GPO?", a: "Group Policy Object — regler i Active Directory der styrer indstillinger og rettigheder for brugere og computere." },
      { q: "Hvad er IAM?", a: "Identity and Access Management — styring af hvem der har adgang til hvilke ressourcer i et system." },
      { q: "Hvad er GRC?", a: "Governance, Risk and Compliance — rammerne for at styre risici og sikre at organisationen overholder regler og standarder." },
      { q: "Hvad er kryptografi?", a: "Teknikker til at beskytte data ved at kode det, så kun autoriserede parter kan læse det." },
    ],
  },
  {
    topic: "Cloud & Serveradmin",
    icon: "🖥️",
    cards: [
      { q: "Hvad er Microsoft Azure?", a: "Microsofts cloud-platform til at hoste applikationer, databaser, VM'er og meget mere." },
      { q: "Hvad er Microsoft Sentinel?", a: "Et cloud-baseret SIEM-værktøj fra Microsoft til at overvåge og reagere på sikkerhedshændelser." },
      { q: "Hvad er SIEM?", a: "Security Information and Event Management — et system der indsamler og analyserer sikkerhedsdata fra hele organisationen." },
      { q: "Hvad er KQL?", a: "Kusto Query Language — et forespørgselssprog brugt i Azure og Microsoft Sentinel til at analysere logdata." },
      { q: "Hvad er Terraform?", a: "Et Infrastructure as Code-værktøj der gør det muligt at oprette og styre cloud-ressourcer via konfigurationsfiler." },
      { q: "Hvad er PowerShell?", a: "Et kommandolinjeværktøj og scriptingsprog fra Microsoft, brugt til automatisering og serveradministration." },
      { q: "Hvad er forskellen på DNS og DHCP?", a: "DNS oversætter domænenavne til IP-adresser. DHCP tildeler automatisk IP-adresser til enheder på et netværk." },
      { q: "Hvad er en NSG Firewall i Azure?", a: "En Network Security Group der fungerer som firewall og kontrollerer hvilken netværkstrafik der tillades ind og ud af Azure-ressourcer." },
    ],
  },
  {
    topic: "AI & Automation",
    icon: "🤖",
    cards: [
      { q: "Hvad er RAG?", a: "Retrieval-Augmented Generation — en teknik hvor en AI-model henter relevant information fra en vidensbase før den genererer et svar, for at gøre svaret mere præcist." },
      { q: "Hvad er MCP?", a: "Model Context Protocol — et standardiseret interface der gør det muligt for AI-modeller at kommunikere med eksterne værktøjer og systemer." },
      { q: "Hvad er et LLM?", a: "Large Language Model — en stor sprogmodel trænet på enorme mængder tekst, fx ChatGPT eller Claude." },
      { q: "Hvad er Back-end Automation?", a: "Automatisering af serverside-processer, fx at håndtere data, sende notifikationer eller kalde API'er uden manuel indgriben." },
      { q: "Hvad er et AI Workflow?", a: "En kæde af automatiserede trin hvor AI bruges til at behandle input, tage beslutninger og producere output — fx at læse en email, analysere den og svare automatisk." },
    ],
  },
  {
    topic: "Netværk",
    icon: "🌐",
    cards: [
      { q: "Hvad er en IP-adresse?", a: "Unik numerisk identifikator (fx 203.0.113.10) der gør det muligt for enheder at finde hinanden på netværket." },
      { q: "Hvad er DNS?", a: "Oversætter domænenavne til IP-adresser. Du skriver google.com, DNS finder IP'en bag." },
      { q: "Hvad er DNS spoofing?", a: "Angreb hvor DNS-poster manipuleres så brugere sendes til falske websites i stedet for de rigtige." },
      { q: "Hvad er en port?", a: "Nummereret kanal (1-65535) på en server. Hver applikation lytter på sin egen port så trafik havner det rigtige sted." },
      { q: "Hvad er standardportene 80, 443 og 3306?", a: "80 er HTTP, 443 er HTTPS, 3306 er MySQL. Standardporte alle systemer kender." },
      { q: "Hvad er et subnet?", a: "En opdeling af netværket i separate sektioner. Frontend i ét subnet, database i et andet, for sikkerhed og isolation." },
      { q: "Hvad er routing?", a: "Bestemmer stien data skal tage mellem subnets. Fungerer som GPS for netværkspakker." },
      { q: "Hvad er en host firewall?", a: "Sidder på den enkelte server og filtrerer trafik ind/ud af den specifikke maskine." },
      { q: "Hvad er en network firewall?", a: "Sidder mellem subnets og filtrerer trafik på netværksniveau før det overhovedet når serverene." },
      { q: "Hvad er NAT?", a: "Lader mange private servere dele én offentlig IP-adresse når de tilgår internettet." },
      { q: "Hvad er en VPC?", a: "Dit eget isolerede afsnit af cloud-udbyderens netværk. Samme koncepter som fysisk netværk, bare som managed service." },
      { q: "Hvad er en Internet Gateway?", a: "Forbinder dine offentlige subnets i en VPC med internettet. Hoveddøren ud." },
      { q: "Hvad er Docker bridge network?", a: "Privat netværk kun på én server. Containere på samme host kan tale med hinanden via containernavne." },
      { q: "Hvad er port mapping i Docker?", a: "Binder en port på host-serveren til en port inde i containeren så ekstern trafik kan nå applikationen." },
      { q: "Hvad er Docker overlay network?", a: "Virtuelt netværk der spænder over flere servere så containere på forskellige hosts kan kommunikere." },
      { q: "Hvad er en Kubernetes pod?", a: "Mindste enhed i Kubernetes. En eller flere containere der deler samme IP. Er midlertidig — kan slettes og genskabes når som helst." },
      { q: "Hvad er en Kubernetes Service?", a: "Giver en stabil IP og DNS-navn foran pods. Pods kan udskiftes i baggrunden uden at forbindelser bryder." },
      { q: "Hvad er Kubernetes Ingress?", a: "Ruter ekstern trafik til de rigtige interne services baseret på URL-sti eller domæne." },
      { q: "Hvad er forskellen på HTTP og HTTPS?", a: "HTTP sender data i klartekst. HTTPS krypterer med SSL/TLS. Al sensitiv trafik skal bruge HTTPS." },
      { q: "Hvad er TCP/IP?", a: "TCP sikrer pålidelig levering af pakker i korrekt rækkefølge. IP finder ruten derhen." },
      { q: "Hvad er DHCP?", a: "Tildeler automatisk IP-adresser til enheder der forbinder til et netværk. Uden det skulle du gøre det manuelt." },
      { q: "Hvad er SSH?", a: "Krypteret fjernlogin til servere. Erstatter Telnet der sendte alt i klartekst." },
      { q: "Hvad er SMB og hvilken sikkerhedsrisiko er der?", a: "Windows-protokol til intern fildeling. Udnyttet af WannaCry-ransomwaren i 2017." },
      { q: "Hvad er forskellen på FTP og SFTP?", a: "FTP overfører filer i klartekst. SFTP krypterer alt via SSH. Brug altid SFTP." },
      { q: "Hvad er RDP og hvilken sikkerhedsrisiko er der?", a: "Fjernadgang til Windows-skrivebord. Svage kodeord og åbne porte er en klassisk indgangsvektor for angribere." },
      { q: "Hvad er forskellen på WPA2 og WPA3?", a: "Begge er krypteringsprotokoller til Wi-Fi. WPA3 er nyere og langt mere modstandsdygtig over for brute-force angreb." },
      { q: "Hvad er IPSec/VPN?", a: "IPSec krypterer al netværkstrafik på pakkeniveau. Bruges i VPN så din internetudbyder ikke kan se hvad du sender." },
      { q: "Hvad er BGP?", a: "Internettets trafikstyringssystem. Fortæller routere verden over hvilke veje der fører til hvilke netværk. En fejl kan tage store tjenester offline." },
      { q: "Hvad er QUIC?", a: "Nyere protokol der erstatter TCP. Reducerer latency ved at minimere handshake-processen. Bruges til streaming og gaming." },
      { q: "Hvad er MQTT?", a: "Letvægtsprotokol til IoT-enheder som smarte termostater og sensorer. Bruger minimal strøm og båndbredde." },
    ],
  },
];
